[project]
name = "cohere-mcp-server"
version = "0.1.0"
description = "Cohere MCP Server"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "cohere>=5.14.0",
    "mcp[cli]>=1.5.0",
]
